build:
    cd /opt/wg-portal && make build

start:
    docker-compose up -d

stop:
    docker-compose down

logs:
    docker-compose logs -f wireguard-vm

shell:
    docker exec -it wireguard-vm bash
